### ISSUE TITLE
Metadata edits not saving to document

### ISSUE THREAD

**Issue by OsmanMutlu** [proycon/foliadocserve#13]
Hi proycon,
This is not going to be much informative, i know, for that i'm sorry.
On a fresh install of flat and foliadocserve(pip install);
I was editing meta tags and most of the time they weren't saving to the folia.xml file. (It saved 3 times out of 20 or so tries)
So i dug into the code and realized that after you do some changes to doc.metadata you assign None to doc. So i put a "doc.save()" in the middle (at line 627 of foliadocserve.py) and my issue was solved.

Maybe this issue is not general and it appeared on my setup for some reason, but i wanted to let you know.

Have a nice day :smiley: 

`                if logfile: traceback.print_tb(exc_traceback, limit=50, file=logfile)
                raise cherrypy.HTTPError(404, "FoLiA error in " + "/".join(docsel) + ": [" + e.__class__.__name__ + "] " + str(e) + "\n\nQuery was: " + rawquery)

            if doc.metadatatype == folia.MetaDataType.NATIVE:
                self.docstore.lastaccess[docsel][sid] = time.time()
                log("[METADATA EDIT ON " + "/".join(docsel)  + "]")
                for key, value in metachanges.items():
                    if value == 'NONE':
                        del doc.metadata[key]
                    else:
                        doc.metadata[key] = value
            else:
                raise cherrypy.HTTPError(404, "Unable to edit metadata on document with non-native metadata type (" + "/".join(docsel)+")")
            doc.save()

        results = [] #stores all results
        xresults = [] #stores results that should be transferred to other sessions as well, i.e. results of adds/edits
        doc = None
        prevdocid = None
        multidoc = False #are the queries over multiple distinct documents?
        format = None
        for query, rawquery in queries:
            try:
                doc = self.docstore[docsel]`

**Comment by proycon** [comment]
Good work, it seems you found a bug indeed! I'll fix it asap

**Comment by proycon** [comment]
(fixed and released)
